version: "3.9"
services:
  web:
    image: node:16-alpine
    command: sh -c "yarn install
                 && echo JWT_TOKEN=$(cat /proc/sys/kernel/random/uuid | sha256sum | cut -d ' ' -f1) > .env 
                 && yarn prisma db push 
                 && yarn prisma db seed 
                 && yarn build && yarn start"
    ports:
      - 3000:3000
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db/thc
    working_dir: /app
    volumes:
      - .:/app
  db:
    image: postgres:alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - db:/var/lib/postgresql/data
volumes:
    db:
