version: "3.9"
services:
  web:
    image: node:16-alpine
    command: sh -c "yarn && yarn prisma db push && yarn prisma db seed && yarn build && yarn start"
    ports:
      - "3000:3000"
    working_dir: /app
    volumes:
      - ./public/uploads:/app/public/uploads
  db:
    image: postgres:alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    volumes:
      - db:/var/lib/postgresql/data
volumes:
  db:
